# Generated by Django 5.0 on 2025-01-27 02:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spotifytoken",
            old_name="token_field",
            new_name="token_type",
        ),
    ]
